import type { Metadata } from "next";

import { Inter as FontSans } from "next/font/google"
import { cn } from "@/lib/utils"
import "../styles/globals.css";
import Navbar from "@/components/Navbar";
import { Toaster } from "@/components/ui/toaster"



import { ThemeProvider } from "@/components/theme-provider"
import TanStackProvider from "@/components/Tanstack-provider";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Next chat app",
  description: "Generated by zain",
};

export const dynamic = 'force-dynamic'
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}>
      

          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            

            <TanStackProvider>
            <Navbar></Navbar>
            {children} 
            </TanStackProvider>
            </ThemeProvider>
            <Toaster />
        </body>
    </html>
  );
}
